version: '2'

services:
  data:
    container_name: "rails-db-data"
    image: busybox
    volumes:
      - ./docker/db/data:/var/lib/mysql
  db:
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    container_name: "rails-db"
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sampleappdb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
    volumes:
      - data
  sampleapp:
    build:
      context: ./
      dockerfile: ./docker/sampleapp/Dockerfile
    container_name: "rails-sampleapp"
    environment:
      TZ: Japan
    command: |
      bundle exec rails server -b 0.0.0.0 -p 8000
    volumes:
      - ./sampleapp:/srv/blog
      - ./docker/sampleapp/log:/var/log
    ports:
      - 8000:8000
    depends_on:
      - data
      - db
